#!/usr/bin/env bash
# Generate js/config.js for GitHub Pages deploy (secrets → file).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/js/config.js"

SUPABASE_URL="${SUPABASE_URL:-}"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-}"
GH_ID="${GH_OAUTH_CLIENT_ID:-}"
GH_OWNER="${GH_REPO_OWNER:-sauravanandb2w}"
GH_NAME="${GH_REPO_NAME:-upsc-current-affairs}"
GH_ALLOWED="${GH_UPLOAD_ALLOWED_USER:-sauravanandb2w}"
GH_SCOPE="${GH_OAUTH_SCOPE:-public_repo}"

if [[ -z "$SUPABASE_URL" || -z "$SUPABASE_ANON_KEY" ]]; then
  echo "warn: SUPABASE_URL or SUPABASE_ANON_KEY missing; writing placeholder config" >&2
  SUPABASE_URL="https://YOUR_PROJECT_ID.supabase.co"
  SUPABASE_ANON_KEY="YOUR_ANON_PUBLIC_KEY"
fi

cat > "$OUT" <<EOF
/** Generated by scripts/generate-config.sh — do not commit */
export const SUPABASE_URL = "$SUPABASE_URL";
export const SUPABASE_ANON_KEY = "$SUPABASE_ANON_KEY";
export const GITHUB_OAUTH_CLIENT_ID = "$GH_ID";
export const GITHUB_REPO_OWNER = "$GH_OWNER";
export const GITHUB_REPO_NAME = "$GH_NAME";
export const GITHUB_UPLOAD_ALLOWED_USER = "$GH_ALLOWED";
export const GITHUB_OAUTH_SCOPE = "$GH_SCOPE";
EOF

echo "wrote $OUT"
