#!/usr/bin/env bash
# Generate js/config.js for GitHub Pages deploy (secrets → file).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/js/config.js"

SUPABASE_URL="${SUPABASE_URL:-}"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-}"

if [[ -z "$SUPABASE_URL" || -z "$SUPABASE_ANON_KEY" ]]; then
  echo "warn: SUPABASE_URL or SUPABASE_ANON_KEY missing; writing placeholder config" >&2
  SUPABASE_URL="https://YOUR_PROJECT_ID.supabase.co"
  SUPABASE_ANON_KEY="YOUR_ANON_PUBLIC_KEY"
fi

cat > "$OUT" <<EOF
/** Generated by scripts/generate-config.sh — do not commit */
export const SUPABASE_URL = "$SUPABASE_URL";
export const SUPABASE_ANON_KEY = "$SUPABASE_ANON_KEY";
EOF

echo "wrote $OUT"
